DROP TABLE IF EXISTS cities;
CREATE TABLE cities(id serial PRIMARY KEY, name VARCHAR(255), population integer);

INSERT INTO cities(name, population) VALUES('Bratislava', 432000);
INSERT INTO cities(name, population) VALUES('Budapest', 1759000);
INSERT INTO cities(name, population) VALUES('Prague', 1280000);
INSERT INTO cities(name, population) VALUES('Warsaw', 1748000);
INSERT INTO cities(name, population) VALUES('Los Angeles', 3971000);
INSERT INTO cities(name, population) VALUES('New York', 8550000);
INSERT INTO cities(name, population) VALUES('Edinburgh', 464000);
INSERT INTO cities(name, population) VALUES('Berlin', 3671000);
insert into cities (name, population) values ('Troitskaya', 55);
insert into cities (name, population) values ('Yangzi', 87);
insert into cities (name, population) values ('Sentul', 46);
insert into cities (name, population) values ('Kampong Thom', 68);
insert into cities (name, population) values ('Mayqayyng', 1);
insert into cities (name, population) values ('Maulavi Bāzār', 8);
insert into cities (name, population) values ('Gandu', 71);
insert into cities (name, population) values ('Tolbazy', 54);
insert into cities (name, population) values ('Vegachí', 22);
insert into cities (name, population) values ('Palhoça', 39);
insert into cities (name, population) values ('Calheta de Nesquim', 91);
insert into cities (name, population) values ('Yantian', 43);
insert into cities (name, population) values ('Isla Pucú', 58);
insert into cities (name, population) values ('Niigata-shi', 14);
insert into cities (name, population) values ('Requião', 14);
insert into cities (name, population) values ('Chenghuang', 52);
insert into cities (name, population) values ('Manzë', 42);
insert into cities (name, population) values ('Malya', 99);
insert into cities (name, population) values ('Kutacane', 25);
insert into cities (name, population) values ('Ongi', 76);
insert into cities (name, population) values ('Utmānzai', 80);
insert into cities (name, population) values ('Nianyushan', 8);
insert into cities (name, population) values ('Uyugan', 38);
insert into cities (name, population) values ('Zlonice', 57);
insert into cities (name, population) values ('Arroyo Seco', 3);
insert into cities (name, population) values ('Tenri', 31);
insert into cities (name, population) values ('Yuyangguan', 17);
insert into cities (name, population) values ('Haninge', 53);
insert into cities (name, population) values ('Abrantes', 39);
insert into cities (name, population) values ('Nowshera Cantonment', 23);
insert into cities (name, population) values ('Abucay', 98);
insert into cities (name, population) values ('Saint Petersburg', 37);
insert into cities (name, population) values ('Los Angeles', 58);
insert into cities (name, population) values ('Gafanha de Aquém', 22);
insert into cities (name, population) values ('Cabannungan Second', 26);
insert into cities (name, population) values ('Merton', 13);
insert into cities (name, population) values ('Nizhnedevitsk', 71);
insert into cities (name, population) values ('Kemiri Daya', 48);
insert into cities (name, population) values ('Phichit', 75);
insert into cities (name, population) values ('Garko', 74);
insert into cities (name, population) values ('Santa Cruz', 82);
insert into cities (name, population) values ('Kalianda', 76);