DROP TABLE IF EXISTS balls;

CREATE TABLE balls (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    color VARCHAR(5) NOT NULL,
    PRIMARY KEY(id)
);

insert into balls (color) values ('White');
insert into balls (color) values ('White');
insert into balls (color) values ('Black');
insert into balls (color) values ('Black');

