package com.hao.postgres;


import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@Slf4j
//@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DDLTest {

    @Test
    public void schema() {

        /*

postgres=# \d organizations
                                  Table "public.organizations"
    Column    |          Type          | Collation | Nullable |             Default
--------------+------------------------+-----------+----------+----------------------------------
 id           | bigint                 |           | not null | generated by default as identity
 active       | boolean                |           | not null |
 country_code | integer                |           |          | 86
 description  | character varying(255) |           |          |
 name         | character varying(64)  |           | not null |
 tenant_id    | character varying(255) |           | not null |
Indexes:
    "organizations_pkey" PRIMARY KEY, btree (id)
    "organizations_ukey_tenant_id_name" UNIQUE CONSTRAINT, btree (tenant_id, name)

         */

    }

}
