package com.hao.postgres.ddl;


import com.hao.postgres.util.CommandRunner;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
//@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DDLTest {


    @Autowired
    CommandRunner commandRunner;

    @Test
    public void schema() {
        commandRunner.describeTable("organizations");
        /*
        postgres=# \d organizations
                                          Table "public.organizations"
            Column    |          Type          | Collation | Nullable |             Default
        --------------+------------------------+-----------+----------+----------------------------------
         id           | bigint                 |           | not null | generated by default as identity
         active       | boolean                |           | not null |
         country_code | integer                |           |          | 86
         description  | character varying(255) |           |          |
         name         | character varying(64)  |           | not null |
         tenant_id    | character varying(255) |           | not null |
        Indexes:
            "organizations_pkey" PRIMARY KEY, btree (id)
            "organizations_ukey_tenant_id_name" UNIQUE CONSTRAINT, btree (tenant_id, name)
         */
    }

}
